// Generated by https://quicktype.io

export interface IAuthenticated {
    accessToken: string;
    User:        IUser;
}

export interface IUser {
    id:        string;
    createdAt: string;
    updatedAt: string;
    nombre:    string;
    apellido:  string;
    email:     string;
    role:      string;
}
