// Generated by https://quicktype.io

export interface IGenre{
    id:        string;
    createdAt: string;
    updatedAt: string;
    imagen:    string;
    nombre:    string;
    slug:      string;
}
