// Generated by https://quicktype.io

import { IUser } from "@modules/auth/interfaces/auth.interface";
import { IAlbum } from "./album.interface";
import { IGenre } from "./genre.interface";

export interface INewSong {
    imagen:    string | ArrayBuffer | null | File;
    cancion:   string | ArrayBuffer | null | File;
    nombre:    string;
    isPrivado: boolean;
    genero:    string;
    album:     string;
    idioma:    string;
}


export interface ISong {
    id:                string;
    createdAt:         string;
    updatedAt:         string;
    imagen:            string;
    nombre:            string;
    slug:              string;
    duracion:          string;
    reproducciones:    number;
    fecha_lanzamiento: string;
    isPrivado:         boolean;
    usuario:           IUser;
    album:             Omit<IAlbum, 'usuario_id'>;
    genero:            IGenre;
}