// Generated by https://quicktype.io

import { ISong } from "./song.interface";

export interface Version {
  id:                string;
  createdAt:         string;
  updatedAt:         string;
  idioma:            string;
  letra:             string;
  nombre_cancion:    string;
  isBase:            boolean;
  estado_traduccion: string;
  cancion:           ISong;
  url_cancion:       string;
}
